// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDkzkcYKaTtcFZiI7eJIJvI6dihIrX8jo',
    appId: '1:1033931715313:web:55d238893ad0d16a4f2f50',
    messagingSenderId: '1033931715313',
    projectId: 'fruit-hub-917d0',
    authDomain: 'fruit-hub-917d0.firebaseapp.com',
    storageBucket: 'fruit-hub-917d0.firebasestorage.app',
    measurementId: 'G-SWVYJLCQLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv6CMbMQG_8KvZuLrUsrlcX_Nrfzkddwo',
    appId: '1:1033931715313:android:149ce47312a9d2724f2f50',
    messagingSenderId: '1033931715313',
    projectId: 'fruit-hub-917d0',
    storageBucket: 'fruit-hub-917d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmz1cZO9U4i9TE3_CjWARDtGoyY4st7yM',
    appId: '1:1033931715313:ios:e9f7c5aa1f64a6bb4f2f50',
    messagingSenderId: '1033931715313',
    projectId: 'fruit-hub-917d0',
    storageBucket: 'fruit-hub-917d0.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmz1cZO9U4i9TE3_CjWARDtGoyY4st7yM',
    appId: '1:1033931715313:ios:e9f7c5aa1f64a6bb4f2f50',
    messagingSenderId: '1033931715313',
    projectId: 'fruit-hub-917d0',
    storageBucket: 'fruit-hub-917d0.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDkzkcYKaTtcFZiI7eJIJvI6dihIrX8jo',
    appId: '1:1033931715313:web:1656cf3472f0c8914f2f50',
    messagingSenderId: '1033931715313',
    projectId: 'fruit-hub-917d0',
    authDomain: 'fruit-hub-917d0.firebaseapp.com',
    storageBucket: 'fruit-hub-917d0.firebasestorage.app',
    measurementId: 'G-6PMR4X48YV',
  );
}
